site:
  title: Nanyang Sites GIS data pool
  description: This site makes available data on Chinese religious sites from across Southeast Asia.
  url: https://nanyang-data.info # No trailing slash!
  shortName: Nanyang Sites GIS data pool

paths:
  repositories: ./repositories # relative to project root

datasets:
  - https://github.com/nanyang-temples/taiwan-public
  - https://github.com/nanyang-temples/thailand-public
  - https://github.com/nanyang-temples/singapore-public
  - https://github.com/nanyang-temples/indonesia-public
  - https://github.com/nanyang-temples/laos-public
